export interface TerminologyItem {
    term: string;
    definition: string;
    category: 'Finance' | 'Fintech' | 'Technology';
}

export const TERMINOLOGY_DB: TerminologyItem[] = [
    // Finance
    { term: 'Arbitrage', definition: 'The simultaneous purchase and sale of the same asset in different markets to profit from tiny differences in the asset\'s listed price.', category: 'Finance' },
    { term: 'Beta', definition: 'A measure of the volatility—or systematic risk—of a security or portfolio compared to the market as a whole.', category: 'Finance' },
    { term: 'Alpha', definition: 'A measure of the active return on an investment, the performance of that investment compared with a suitable market index.', category: 'Finance' },
    { term: 'Capital Asset Pricing Model (CAPM)', definition: 'A model that describes the relationship between systematic risk and expected return for assets, particularly stocks.', category: 'Finance' },
    { term: 'Weighted Average Cost of Capital (WACC)', definition: 'A calculation of a firm\'s cost of capital in which each category of capital is proportionately weighted.', category: 'Finance' },
    { term: 'Internal Rate of Return (IRR)', definition: 'A metric used in financial analysis to estimate the profitability of potential investments.', category: 'Finance' },
    { term: 'Net Present Value (NPV)', definition: 'The difference between the present value of cash inflows and the present value of cash outflows over a period of time.', category: 'Finance' },
    { term: 'Yield to Maturity (YTM)', definition: 'The total return anticipated on a bond if the bond is held until it matures.', category: 'Finance' },
    { term: 'Duration', definition: 'A measure of the sensitivity of the price of a bond or other debt instrument to a change in interest rates.', category: 'Finance' },
    { term: 'Convexity', definition: 'A measure of the curvature in the relationship between bond prices and bond yields that demonstrates how the duration of a bond changes as the interest rate changes.', category: 'Finance' },
    { term: 'Leverage Ratio', definition: 'Any one of several financial measurements that look at how much capital comes in the form of debt (loans) or assesses the ability of a company to meet its financial obligations.', category: 'Finance' },
    { term: 'Price-to-Earnings Ratio (P/E)', definition: 'The ratio for valuing a company that measures its current share price relative to its per-share earnings.', category: 'Finance' },
    { term: 'Enterprise Value (EV)', definition: 'A measure of a company\'s total value, often used as a more comprehensive alternative to equity market capitalization.', category: 'Finance' },
    { term: 'Free Cash Flow (FCF)', definition: 'The cash a company generates after taking into consideration cash outflows that support its operations and maintain its capital assets.', category: 'Finance' },
    { term: 'Securitization', definition: 'The procedure where an issuer designs a marketable financial instrument by merging or pooling various financial assets into one group.', category: 'Finance' },
    { term: 'Credit Default Swap (CDS)', definition: 'A financial derivative or contract that allows an investor to "swap" or offset their credit risk with that of another investor.', category: 'Finance' },
    { term: 'Derivative', definition: 'A financial security with a value that is reliant upon or derived from an underlying asset or group of assets.', category: 'Finance' },
    { term: 'Option (Call/Put)', definition: 'A financial derivative that represents a contract sold by one party (the option writer) to another party (the option holder) offering the right, but not the obligation, to buy (call) or sell (put) a security at an agreed-upon price.', category: 'Finance' },
    { term: 'Futures Contract', definition: 'A legal agreement to buy or sell a particular commodity asset, or security at a predetermined price at a specified time in the future.', category: 'Finance' },
    { term: 'Hedging', definition: 'A risk management strategy employed to offset losses in investments by taking an opposite position in a related asset.', category: 'Finance' },

    // Fintech
    { term: 'AISP (Account Information Service Provider)', definition: 'A service provider that can access account information from banks and other financial institutions with the user\'s explicit consent.', category: 'Fintech' },
    { term: 'PISP (Payment Initiation Service Provider)', definition: 'A service provider that can initiate a payment on behalf of the user, with their consent, directly from their bank account.', category: 'Fintech' },
    { term: 'CBDC (Central Bank Digital Currency)', definition: 'A digital form of central bank money that is different from balances in traditional reserve or settlement accounts.', category: 'Fintech' },
    { term: 'Embedded Finance', definition: 'The integration of financial services into non-financial offerings, such as a retailer offering insurance or a ride-sharing app offering payments.', category: 'Fintech' },
    { term: 'Fintech Sandbox', definition: 'A framework set up by a regulator that allows FinTech startups and other innovators to conduct live experiments in a controlled environment under a regulator\'s supervision.', category: 'Fintech' },
    { term: 'Open Banking API', definition: 'Application Programming Interfaces that allow third-party developers to build applications and services around the financial institution.', category: 'Fintech' },
    { term: 'Smart Contract', definition: 'A self-executing contract with the terms of the agreement between buyer and seller being directly written into lines of code.', category: 'Fintech' },
    { term: 'Oracles (in Blockchain)', definition: 'Third-party services that provide smart contracts with external information. They serve as bridges between blockchains and the outside world.', category: 'Fintech' },
    { term: 'Layer 2 Scaling', definition: 'A collective term for solutions designed to help scale your application by handling transactions off the Ethereum Mainnet (Layer 1).', category: 'Fintech' },
    { term: 'Zero Knowledge Proofs', definition: 'A method by which one party (the prover) can prove to another party (the verifier) that they know a value x, without conveying any information apart from the fact that they know the value x.', category: 'Fintech' },
    { term: 'Tokenization of Real World Assets (RWA)', definition: 'The process of converting rights to an asset with economic value into a digital token on a blockchain.', category: 'Fintech' },
    { term: 'RegTech', definition: 'The management of regulatory processes within the financial industry through technology. The main functions of RegTech include regulatory monitoring, reporting, and compliance.', category: 'Fintech' },
    { term: 'SupTech', definition: 'Supervisory Technology; the use of innovative technology by supervisory agencies to support supervision.', category: 'Fintech' },
    { term: 'Robo Underwriting', definition: 'The use of automated algorithms to evaluate the risk of lending to a borrower.', category: 'Fintech' },
    { term: 'Alternative Credit Scoring', definition: 'The use of non-traditional data sources (like utility payments, rental history, or social media usage) to assess creditworthiness.', category: 'Fintech' },
    { term: 'Biometric Payments', definition: 'Point of sale (POS) technology that uses biometric authentication (fingerprint, facial recognition) to identify the user and authorize the deduction of funds from a bank account.', category: 'Fintech' },
    { term: 'NFC (Near Field Communication) Payments', definition: 'Contactless payments that use near-field communication technology to exchange data between readers and payment devices like Apple Pay and Google Pay.', category: 'Fintech' },
    { term: '3D Secure', definition: 'A security protocol that adds an extra layer of protection for online credit and debit card transactions.', category: 'Fintech' },
    { term: 'Dynamic CVV', definition: 'A technology that changes the CVV code on a credit card periodically (e.g., every hour) to prevent fraud.', category: 'Fintech' },
    { term: 'Quantum Safe Cryptography', definition: 'Cryptographic algorithms that are thought to be secure against an attack by a quantum computer.', category: 'Fintech' },
    { term: 'Digital Wallet', definition: 'A software-based system that securely stores users\' payment information and passwords for numerous payment methods and websites.', category: 'Fintech' },
    { term: 'UPI (Unified Payments Interface)', definition: 'An instant real-time payment system developed by National Payments Corporation of India facilitating inter-bank peer-to-peer and person-to-merchant transactions.', category: 'Fintech' },
    { term: 'Neobank', definition: 'A type of direct bank that operates exclusively online without traditional physical branch networks.', category: 'Fintech' },
    { term: 'Payment Gateway', definition: 'A merchant service provided by an e-commerce application service provider that authorizes credit card or direct payments processing for e-businesses.', category: 'Fintech' },
    { term: 'Buy Now Pay Later (BNPL)', definition: 'A type of short-term financing that allows consumers to make purchases and pay for them at a future date, often interest-free.', category: 'Fintech' },
    { term: 'Credit Scoring', definition: 'A statistical analysis performed by lenders and financial institutions to determine the creditworthiness of a person or a small, owner-operated business.', category: 'Fintech' },
    { term: 'Peer-to-Peer (P2P) Lending', definition: 'The practice of lending money to individuals or businesses through online services that match lenders with borrowers.', category: 'Fintech' },
    { term: 'Alternative Data', definition: 'Information used to evaluate creditworthiness that is not typically included in traditional credit reports, such as rent payments, utility bills, and social media activity.', category: 'Fintech' },
    { term: 'Robo-advisor', definition: 'Digital platforms that provide automated, algorithm-driven financial planning services with little to no human supervision.', category: 'Fintech' },
    { term: 'Fractional Investing', definition: 'A strategy that allows investors to buy a portion of a stock or other asset rather than the full share, making expensive assets more accessible.', category: 'Fintech' },
    { term: 'Crowdfunding', definition: 'The practice of funding a project or venture by raising small amounts of money from a large number of people, typically via the Internet.', category: 'Fintech' },
    { term: 'Blockchain', definition: 'A decentralized, distributed and public digital ledger that is used to record transactions across many computers so that the record cannot be altered retroactively.', category: 'Fintech' },
    { term: 'Cryptocurrency', definition: 'A digital or virtual currency that is secured by cryptography, which makes it nearly impossible to counterfeit or double-spend.', category: 'Fintech' },
    { term: 'Stablecoin', definition: 'A cryptocurrency designed to have a relatively stable price, typically through being pegged to a commodity or currency or having its supply regulated by an algorithm.', category: 'Fintech' },
    { term: 'Decentralized Finance (DeFi)', definition: 'Blockchain-based form of finance that does not rely on central financial intermediaries such as brokerages, exchanges, or banks to offer traditional financial instruments.', category: 'Fintech' },
    { term: 'Tokenization', definition: 'The process of replacing sensitive data with unique identification symbols that retain all the essential information about the data without compromising its security.', category: 'Fintech' },
    { term: 'Open Banking', definition: 'A banking practice that provides third-party financial service providers open access to consumer banking, transaction, and other financial data from banks and non-bank financial institutions through the use of application programming interfaces (APIs).', category: 'Fintech' },
    { term: 'Know Your Customer (KYC)', definition: 'The process of a business verifying the identity of its clients and assessing potential risks of illegal intentions for the business relationship.', category: 'Fintech' },
    { term: 'InsurTech', definition: 'The use of technology innovations designed to squeeze out savings and efficiency from the current insurance industry model.', category: 'Fintech' },

    // Technology
    { term: 'AIOps', definition: 'Artificial Intelligence for IT Operations; the application of AI to enhance IT operations.', category: 'Technology' },
    { term: 'Zero Trust Architecture', definition: 'A security model that requires strict identity verification for every person and device trying to access resources on a private network, regardless of whether they are sitting within or outside of the network perimeter.', category: 'Technology' },
    { term: 'Homomorphic Encryption', definition: 'A form of encryption that permits users to perform computations on its encrypted data without first decrypting it.', category: 'Technology' },
    { term: 'Federated Learning', definition: 'A machine learning technique that trains an algorithm across multiple decentralized edge devices or servers holding local data samples, without exchanging them.', category: 'Technology' },
    { term: 'Edge AI', definition: 'The deployment of AI applications in devices throughout the physical world, close to where data is created, rather than in a centralized cloud.', category: 'Technology' },
    { term: 'Multimodal AI', definition: 'Artificial intelligence that can understand and generate information using multiple modalities, such as text, images, audio, and video.', category: 'Technology' },
    { term: 'Vector Database', definition: 'A database designed to store and query vector embeddings, which are mathematical representations of data used in machine learning.', category: 'Technology' },
    { term: 'Retrieval-Augmented Generation (RAG)', definition: 'An AI framework that retrieves facts from an external knowledge base to ground large language models (LLMs) on the most accurate, up-to-date information.', category: 'Technology' },
    { term: 'Digital Twin', definition: 'A virtual model designed to accurately reflect a physical object.', category: 'Technology' },
    { term: 'Kubernetes', definition: 'An open-source container orchestration system for automating software deployment, scaling, and management.', category: 'Technology' },
    { term: 'Service Mesh', definition: 'A dedicated infrastructure layer for facilitating service-to-service communications between services or microservices.', category: 'Technology' },
    { term: 'Event-Driven Architecture', definition: 'A software architecture paradigm promoting the production, detection, consumption of, and reaction to events.', category: 'Technology' },
    { term: 'Serverless Computing', definition: 'A cloud computing execution model in which the cloud provider runs the server, and dynamically manages the allocation of machine resources.', category: 'Technology' },
    { term: 'Infrastructure as Code (IaC)', definition: 'The process of managing and provisioning computer data centers through machine-readable definition files, rather than physical hardware configuration or interactive configuration tools.', category: 'Technology' },
    { term: 'Observability', definition: 'A measure of how well internal states of a system can be inferred from knowledge of its external outputs.', category: 'Technology' },
    { term: 'Data Lakehouse', definition: 'A new, open data management architecture that combines the flexibility, cost-efficiency, and scale of data lakes with the data management and ACID transactions of data warehouses.', category: 'Technology' },
    { term: 'Differential Privacy', definition: 'A system for publicly sharing information about a dataset by describing the patterns of groups within the dataset while withholding information about individuals in the dataset.', category: 'Technology' },
    { term: 'Quantum Computing', definition: 'A type of computing that uses quantum-mechanical phenomena, such as superposition and entanglement, to perform data operations.', category: 'Technology' },
    { term: 'Extended Reality (XR)', definition: 'An umbrella term encompassing augmented reality (AR), virtual reality (VR), and mixed reality (MR).', category: 'Technology' },
    { term: 'Software-Defined Vehicles', definition: 'Vehicles whose features and functions are primarily enabled through software, a result of the ongoing transformation of the automotive industry.', category: 'Technology' },
];
